### ISSUE TITLE
Didn't start ?

### ISSUE THREAD

**Issue by profesionalleet1337** [mishakorzik/mask-url#1]
I cant start the instrument ..
When I type :  cd mask-url
 python3 mask.py
 -> its give me that : 
  File "/home/x/mask-url/mask.py", line 4
    d
     ^
SyntaxError: invalid syntax

And I cant run the mask tool ?

**Comment by mishakorzik** [comment]
I fixed

**Comment by profesionalleet1337** [comment]
> I fixed

I write these :
cd mask-url
python3 mask.py 
- > How u said in the instruction, but again its not work for me ..
x@cloudshell:~/mask-url$ python3 mask.py
  File "/home/jx/mask-url/mask.py", line 4
    d
     ^
SyntaxError: invalid syntax

**Comment by mishakorzik** [comment]
Reinstall tool

**Comment by profesionalleet1337** [comment]
> Reinstall tool

Yeah, its work, but only masking normal website, for exapmple If i type youtube.com/ or something like that it will mask him which option I click, but when I put link generated from phishing tool, like zpisher or something like that, it doesn't want to mask with any of the option's.. If i used cloudflare - https://xxx-xxx-xxx-xxx.trycloudflare.com ( from phishing tools ) it said that is "black marked or something like that" If I use another provider, it's just don't generate them. I mean ,maybe the APi you use, only work for normal site's, but there is no point of masking the "suspicious link" from tools, because it don't work for me ?
